/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as UnauthedRouteImport } from './app/_unauthed'
import { Route as AuthedRouteImport } from './app/_authed'
import { Route as IndexRouteImport } from './app/index'
import { Route as UnauthedSignUpIndexRouteImport } from './app/_unauthed/sign-up/index'
import { Route as UnauthedSignInIndexRouteImport } from './app/_unauthed/sign-in/index'
import { Route as UnauthedResetPasswordIndexRouteImport } from './app/_unauthed/reset-password/index'
import { Route as AuthedProductsIndexRouteImport } from './app/_authed/products/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const UnauthedRoute = UnauthedRouteImport.update({
  id: '/_unauthed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthedSignUpIndexRoute = UnauthedSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => UnauthedRoute,
} as any)
const UnauthedSignInIndexRoute = UnauthedSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => UnauthedRoute,
} as any)
const UnauthedResetPasswordIndexRoute =
  UnauthedResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => UnauthedRoute,
  } as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products': typeof AuthedProductsIndexRoute
  '/reset-password': typeof UnauthedResetPasswordIndexRoute
  '/sign-in': typeof UnauthedSignInIndexRoute
  '/sign-up': typeof UnauthedSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products': typeof AuthedProductsIndexRoute
  '/reset-password': typeof UnauthedResetPasswordIndexRoute
  '/sign-in': typeof UnauthedSignInIndexRoute
  '/sign-up': typeof UnauthedSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_unauthed': typeof UnauthedRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_unauthed/reset-password/': typeof UnauthedResetPasswordIndexRoute
  '/_unauthed/sign-in/': typeof UnauthedSignInIndexRoute
  '/_unauthed/sign-up/': typeof UnauthedSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/products'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/products'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_unauthed'
    | '/api/auth/$'
    | '/_authed/products/'
    | '/_unauthed/reset-password/'
    | '/_unauthed/sign-in/'
    | '/_unauthed/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  UnauthedRoute: typeof UnauthedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthed': {
      id: '/_unauthed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthed/sign-up/': {
      id: '/_unauthed/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthedSignUpIndexRouteImport
      parentRoute: typeof UnauthedRoute
    }
    '/_unauthed/sign-in/': {
      id: '/_unauthed/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnauthedSignInIndexRouteImport
      parentRoute: typeof UnauthedRoute
    }
    '/_unauthed/reset-password/': {
      id: '/_unauthed/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof UnauthedResetPasswordIndexRouteImport
      parentRoute: typeof UnauthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface UnauthedRouteChildren {
  UnauthedResetPasswordIndexRoute: typeof UnauthedResetPasswordIndexRoute
  UnauthedSignInIndexRoute: typeof UnauthedSignInIndexRoute
  UnauthedSignUpIndexRoute: typeof UnauthedSignUpIndexRoute
}

const UnauthedRouteChildren: UnauthedRouteChildren = {
  UnauthedResetPasswordIndexRoute: UnauthedResetPasswordIndexRoute,
  UnauthedSignInIndexRoute: UnauthedSignInIndexRoute,
  UnauthedSignUpIndexRoute: UnauthedSignUpIndexRoute,
}

const UnauthedRouteWithChildren = UnauthedRoute._addFileChildren(
  UnauthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  UnauthedRoute: UnauthedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
